version: '3.9'

# docker-compose up -d
# docker-compose down
# docker rm $(docker ps -a -q) && docker volume prune -f

# mongo
# use golang
# db.repos.find().pretty()

services:
  mongodb:
    image: 'mongo:5'
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=golang
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/golang --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_container
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/golang

volumes:
  mongodb_data: